kuduMasterAddresses: ["localhost"]
kuduTSInstance: "ktsd"

server:
  type: default
  applicationContextPath: "/api"
  applicationConnectors:
    - type: http
      port: 4242

logging:
  level: INFO
  loggers:
    org.kududb.ts: INFO

  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

bench:
  ktsdHost: "localhost"
  ktsdPort: 4242
  metrics: [
              "metric00",
              "metric01",
              "metric02",
              "metric03",
              "metric04",
              "metric05",
              "metric06",
              "metric07",
              "metric08",
              "metric09",
           ]
  tags:
    host: [ "host00", "host01", "host02", "host03" ]
    dc: [ "dc00", "dc01", "dc02", "dc03" ]
  start: 1451606400000 # 2016-01-01T00:00:00
  end: 1451692800000 # 2016-01-02T00:00:00
  sampleFrequency: 1
  httpClient:
    keepAlive: "10s"
    timeout: "10s"
